// Centralized English strings for the Rayarchy UI. Keeping every label in one
// file makes future i18n a mechanical change instead of a refactor.
.pragma library

const strings = {
  appTitle: "Rayarchy",
  menuServers: "Servers",
  menuSubscription: "Subscription",
  menuSetting: "Setting",
  menuHelp: "Help",
  menuReload: "Reload",
  menuClose: "Close",
  menuExit: "Exit",

  addVmess: "Add VMess server",
  addVless: "Add VLESS server",
  addShadowsocks: "Add Shadowsocks server",
  addSocks: "Add SOCKS server",
  addHttp: "Add HTTP server",
  addTrojan: "Add Trojan server",
  addHysteria2: "Add Hysteria2 server",
  addTuic: "Add TUIC server",
  addWireguard: "Add WireGuard server",
  addAnytls: "Add Anytls server",
  addNaive: "Add Naive server",
  addCustom: "Add custom config",
  addCustomOutbound: "Add custom outbound",
  addPolicyGroup: "Add policy group",
  addProxyChain: "Add proxy chain",
  addViaClipboard: "Add server via clipboard",
  addViaImage: "Add server via image",
  importFromClipboard: "Import from clipboard",
  importFromImage: "Import from image",

  subSetting: "Subscription setting",
  subUpdate: "Update all subscriptions",
  subUpdateViaProxy: "Update all subscriptions via proxy",
  subUpdateCurrent: "Update current subscription",
  subUpdateCurrentViaProxy: "Update current subscription via proxy",

  optSetting: "Option setting",
  routingSetting: "Routing setting",
  dnsSetting: "DNS setting",
  fullConfigTemplate: "Full config template",
  backupRestore: "Backup and restore",
  clearServerStats: "Clear server statistics",
  clearServerStats: "Clear server statistics",
  openFileLocation: "Open the file location",
  checkUpdate: "Check for updates",
  regionalDefault: "Regional preset: default",
  regionalRussia: "Regional preset: Russia",
  regionalIran: "Regional preset: Iran",

  setDefaultServer: "Set as default",
  editServer: "Edit server",
  copyServer: "Copy server",
  removeServer: "Remove server",
  removeDuplicate: "Remove duplicate",
  removeInvalid: "Remove invalid result",
  tcping: "Tcping",
  realPing: "Real ping",
  udpTest: "UDP test",
  speedTest: "Speed test",
  mixedTest: "Mixed test",
  fastRealPing: "Fast real ping",
  sortByDelay: "Sort by delay",
  moveToGroup: "Move to group",
  moveTop: "Move to top",
  moveUp: "Move up",
  moveDown: "Move down",
  moveBottom: "Move to bottom",
  selectAll: "Select all",
  shareServer: "Share server",
  exportConfig: "Export config",
  exportShareUrl: "Share URL",
  exportShareUrlBase64: "Share URL (base64)",
  exportInnerUri: "Inner URI",
  genGroupAll: "Generate group (all servers)",
  genGroupRegion: "Generate group (region)",

  colConfigType: "Type",
  colRemarks: "Remarks",
  colAddress: "Address",
  colPort: "Port",
  colNetwork: "Network",
  colSecurity: "TLS",
  colSub: "Subscription",
  colDelay: "Delay",
  colSpeed: "Speed",
  colIp: "IP",
  colTodayUp: "↑ Today",
  colTodayDown: "↓ Today",
  colTotalUp: "↑ Total",
  colTotalDown: "↓ Total",

  tabServers: "Servers",
  tabMsg: "Msg",
  tabProxies: "Proxies",
  tabConnections: "Connections",

  statusRunning: "Running server",
  statusNotConnected: "Not connected",
  statusInbound: "Inbound",
  statusTun: "TUN",
  statusSystemProxy: "System proxy",
  statusRouting: "Routing",
  statusClear: "Clear",
  statusSet: "Set",
  statusNoChange: "No change",
  statusProxy: "Proxy",
  statusDirect: "Direct",
  statusBlock: "Block",
  statusAvailable: "Checking availability…",

  runningConnecting: "Connecting…",
  runningConnected: "Connected",
  runningDisconnected: "Disconnected",
  runningFailed: "Connection failed",

  msgFilter: "Filter",
  msgCopy: "Copy",
  msgClear: "Clear",
  msgAutoRefresh: "Auto refresh",
  msgScrollToEnd: "Scroll to end",
  msgEmpty: "No messages",

  ok: "OK",
  cancel: "Cancel",
  save: "Save",
  delete: "Delete",
  close: "Close",
  confirm: "Confirm",
  yes: "Yes",
  no: "No",
  apply: "Apply",
  refresh: "Refresh",
  reload: "Reload",
  add: "Add",
  edit: "Edit",
  remove: "Remove",
  search: "Search",
  done: "Done",
  connect: "Connect",
  disconnect: "Disconnect",
  name: "Remarks",
  address: "Address",
  port: "Port",
  protocol: "Protocol",
  enabled: "Enabled",
  disabled: "Disabled",
  favorite: "Favorite",
  group: "Group",
  filter: "Filter",
  more: "More",

  searchPlaceholder: "Filter servers…",
  subAdd: "Add subscription",
  subEdit: "Edit subscription",
  subDelete: "Delete subscription",
  subUrl: "URL",
  subAutoUpdate: "Auto update",
  subLastRefresh: "Last refresh",
  subNever: "Never",
  subRefresh: "Update now",
  subDisabled: "Disabled",
  subConvert: "Convert",
  subUserAgent: "User agent",

  settingGeneral: "General",
  settingCore: "Core",
  settingSpeed: "Speed test",
  settingTun: "TUN",
  settingUi: "UI",
  settingLocalPort: "Local port",
  settingConnectionMode: "Connection mode",
  settingPreferredCore: "Preferred core",
  settingKillSwitch: "Kill switch",
  settingDnsLeak: "DNS leak protection",
  settingLanBypass: "LAN bypass",
  settingRetention: "Health retention (hours)",
  settingModeSystemProxy: "System proxy",
  settingModeLocal: "Local only",
  settingModeTun: "TUN",
  settingModeTransparent: "Transparent",
  settingCoreAuto: "Auto",
  settingCoreXray: "Xray",
  settingCoreSingBox: "sing-box",

  routingRule: "Routing rule",
  routingAddRule: "Add rule",
  routingDeleteRule: "Delete rule",
  routingMatchType: "Match type",
  routingValue: "Value",
  routingAction: "Action",
  routingTypeDomain: "Domain",
  routingTypeDomainSuffix: "Domain suffix",
  routingTypeDomainKeyword: "Domain keyword",
  routingTypeCidr: "CIDR",
  routingTypeIp: "IP",

  dnsSimple: "Simple DNS",
  dnsDirect: "Direct DNS",
  dnsRemote: "Remote DNS",
  dnsBootstrap: "Bootstrap DNS",
  dnsFakeIp: "FakeIP",
  dnsSystemHosts: "Use system hosts",
  dnsCommonHosts: "Add common hosts",

  serverEditTitle: "Server",
  serverEditName: "Remarks",
  serverEditAddress: "Address",
  serverEditPort: "Port",
  serverEditSecurity: "Security",
  serverEditNetwork: "Network",
  serverEditTls: "TLS",
  serverEditNone: "None",
  serverEditCoreType: "Core type",
  serverEditUuid: "UUID / ID",
  serverEditPassword: "Password",
  serverEditUser: "Username",
  serverEditMethod: "Method",
  serverEditFlow: "Flow",
  serverEditSni: "SNI",
  serverEditHost: "Host",
  serverEditPath: "Path",
  serverEditAlpn: "ALPN",
  serverEditFingerprint: "Fingerprint",
  serverEditPublicKey: "Public key",
  serverEditShortId: "Short ID",
  serverEditSpiderX: "SpiderX",
  serverEditObfs: "Obfuscation",
  serverEditObfsPassword: "Obfuscation password",
  serverEditMtu: "MTU",
  serverEditPrivateKey: "Private key",
  serverEditLocalAddress: "Local address",
  serverEditMembers: "Members",
  serverEditStrategy: "Strategy",
  serverEditRaw: "Custom config (JSON)",
  serverEditInvalid: "Please fill in the required fields",
  serverEditSaved: "Server saved",

  profilesSelectTitle: "Select profiles",
  profilesSelectInclude: "Include types",

  qrShareTitle: "Share server",
  qrCopyPayload: "Copy",

  jsonTitle: "JSON",
  jsonFormat: "Format",
  jsonCopy: "Copy",
  jsonPaste: "Paste",

  backupTitle: "Backup and restore",
  backupExport: "Export backup",
  backupImport: "Import backup",
  backupDone: "Backup complete",
  backupRestored: "Backup restored",

  checkUpdateTitle: "Check for updates",
  checkOnly: "Check only",
  checkUpdateNow: "Check & update",
  coreInstalled: "Installed",
  coreMissing: "Missing",
  coreUpToDate: "Up to date",

  tunNotAvailable: "TUN requires the rayarchy-helper binary (run setup.sh to install it)",
  daemonUnreachable: "The Rayarchy daemon could not be reached. Run setup.sh to install the backend.",
  backendNotInstalled: "Rayarchy backend is not installed or not running",
  connectFailed: "Connection failed",
  disconnected: "Disconnected",
  connectedSummary: "Connected",

  yesNoTitle: "Confirm",
  loading: "Loading…",
  empty: "No servers yet — add one via the Servers menu.",
  retry: "Retry",
  copyEnv: "Copy proxy environment",
  trayShow: "Show Rayarchy",
  trayHide: "Hide window",
}

function tr(key) {
  return strings[key] !== undefined ? strings[key] : key
}